### PR TITLE
Minor changes to your test project.

### PR DESCRIPTION
**Pull request by dlemstra**
Cool to see that you are playing with both projects I work on. This patch changes some Magick.NET things. It removes the size calculation because you don't need it. I also added a call to Strip to reduce the size of the output file.

Not sure if you know but Magick.NET only works on Windows at the moment in .NET Core. I could really use some help (*hint*) to add support for Linux and Mac 😄 .

### CODE REVIEW

**Comment by bleroy** [comment]
Thanks. Yes, I know that Magick.NET is Windows only at the moment. This is for a blog post that will compare all those approaches.

**Comment by bleroy** [comment]
So what are your main concerns with x-plat support?

**Comment by dlemstra** [comment]
My main concern with x-plat support is getting it to compile. Magick.NET uses the ImageMagick library through a DllImport. One of the projects creates a native dll that statically links the ImageMagick library files. These .lib files are created with a build script that takes the various projects (https://github.com/dlemstra/Magick.NET/blob/master/ImageMagick/Source/Checkout.sh) and uses a tool of the ImageMagick project to create a solution and build it. I would need a script that builds all the projects and creates library files for Linux/Mac that I can statically link. I am not really a Linux/Mac expert so I could use some help to get the libraries compiled and linked into the Magick.NET.Native project. Once that's done it should be really easy to change the rest of the project to correctly call the native library.

**Comment by bleroy** [comment]
OK, so I don't really know how to do that either, but I can mention it in my post. You should probably also add that information to the existing ticket (https://github.com/dlemstra/Magick.NET/issues/16), that I'll link to. Does this sound good?

**Comment by dlemstra** [comment]
That would be great 💯! A link to that issue would be awesome. I also added the explanation to the issue. Thanks for telling me to do that 🙌

**Pull request merged**
