### PR TITLE
Update SkiaSharp benchmarks

### PR DESCRIPTION
**Pull request by dylanvdmerwe**
Update SkiaSharp dependency and show another way of resizing benchmarks with different speed and quality characteristics.

### CODE REVIEW

**Comment by bleroy** [comment]
Thanks, I really appreciate your taking the time. I'm hoping to be able to test that and integrate it back to the post later this week.

**Comment by dylanvdmerwe** [comment]
No worries! I was not liking the quality of the resized images produced by the canvas method, so I did some researching on other methods. The quality seems much better using bitmap resizing, but at the cost of some performance. 

Let me know what you think :)

**Comment by dylanvdmerwe** [comment]
Any feedback on your comparisons?

**Comment by bleroy** [comment]
I'm sorry, it's been a crazy week, and I've had zero time to look at this like I intended to. It'll happen though.

**Comment by bleroy** [comment]
Running SkiaSharp on .NET Core benchmark now. Looking good so far. Perf is on-par with Mono.

**Pull request merged**
